run:
  timeout: 5m
  go: "1.21"

linters-settings:
  goimports:
    local-prefixes: healthcheck
  
  govet:
    enable-all: true
    disable:
      - fieldalignment # can be overly pedantic for this project
  
  gocyclo:
    min-complexity: 15
  
  misspell:
    locale: US
  
  lll:
    line-length: 120

linters:
  enable:
    - goimports     # automatically format imports
    - govet         # standard go vet checks
    - ineffassign   # detect ineffectual assignments
    - misspell      # find commonly misspelled words
    - gocyclo       # compute cyclomatic complexities
    - gofmt         # check if code is gofmt-ed
    - revive        # fast, configurable, extensible, flexible linter
    - staticcheck   # advanced go linter
    - unused        # check for unused constants, variables, functions and types
    - errcheck      # check for unchecked errors
    - gosimple      # simplify code
    - typecheck     # type-check Go code
    - lll           # check line length
  
  disable: []

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - lll
    
    # Exclude known false positives
    - text: "Error return value of .((os\\.)?std(out|err)\\..*|.*Close|.*Flush|os\\.Remove(All)?|.*printf?|os\\.(Un)?Setenv). is not checked"
      linters:
        - errcheck
  
  max-issues-per-linter: 0
  max-same-issues: 0